### ISSUE TITLE
OpenWeatherMap API has changed

### ISSUE THREAD

**Issue by jkissell** [bkury/OpenWeatherMap.bundle#1]
This plugin no longer works.  

The OpenWeatherMap API is wanting this format: 
http://api.openweathermap.org/data/2.5/forecast/city?id=524901&APPID=1111111111 

However, this code is set to use this:
http://api.openweathermap.org/data/2.5%s?q=City,US

**Comment by bkury** [comment]
thanks for reporting ... should be fixed with the latest commit :
- Added OpenWeatherMap AppID Support
- Added PLEX Web/iPhone App Support
- Fixed GeoIP Lookup
